GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/630785ab2e2c09d05838571

###
GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/630270da30af14081bd17f95

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "khiem",  
  "number": "123"
}

###
PUT http://localhost:3001/api/persons/6302731e0b1e291c2f472e65
Content-Type: application/json

{
  "name": "Arto Vihavainen",
  "number": "123569"
}
